use library;

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
    ISBN    VARCHAR(13) NOT NULL, 
    Title    VARCHAR(100),
    Issue_No    INT,
    Subject      VARCHAR(40),
    Binding    VARCHAR(15),
    Type  VARCHAR(15),
    PRIMARY KEY (ISBN)
);

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR (
    ISBN    VARCHAR(13) NOT NULL, 
    Author_Name    VARCHAR(40),
    PRIMARY KEY (ISBN, Author_Name)
);

DROP TABLE IF EXISTS CATALOGUE;
CREATE TABLE CATALOGUE (
    ISBN    VARCHAR(13) NOT NULL, 
    Description    VARCHAR(500),
    PRIMARY KEY (ISBN)
);

DROP TABLE IF EXISTS COPIES;
CREATE TABLE COPIES (
    ISBN    VARCHAR(13) NOT NULL, 
    Num_Of_Copies    INT,
    PRIMARY KEY (ISBN)
);

ALTER TABLE AUTHOR ADD CONSTRAINT fk_author_book FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN) ON DELETE CASCADE;
ALTER TABLE CATALOGUE ADD CONSTRAINT fk_catalogue_book FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN) ON DELETE CASCADE;
ALTER TABLE COPIES ADD CONSTRAINT fk_copies_book FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN) ON DELETE CASCADE;

DROP TABLE IF EXISTS STAFF;
CREATE TABLE STAFF (
    S_ID    INT NOT NULL, 
    Name    VARCHAR(20) NOT NULL,
    S_SSN   CHAR(9) NOT NULL,
    Librarian_Type VARCHAR(25) NOT NULL,
    Experience INT,
    Associate_Rank INT,
    Typing_Speed DECIMAL(4,2),
    Degree_Pr VARCHAR(15),
    RL_level VARCHAR(4),
    PRIMARY KEY (S_ID)
);

DROP TABLE IF EXISTS MEMBER;
CREATE TABLE MEMBER (
    SSN    CHAR(9) NOT NULL,
    Name    CHAR(25) NOT NULL,
    Email_ID CHAR(40) NOT NULL, 
    is_Faculty  VARCHAR(3),
    Mem_ID   CHAR(11) NOT NULL,
    Validity DATE,
    S_ID INT,
    PRIMARY KEY (SSN)
);

ALTER TABLE MEMBER ADD CONSTRAINT fk_member_staff FOREIGN KEY (S_ID) REFERENCES STAFF(S_ID) ON DELETE SET NULL;

DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS (
    SSN    CHAR(9) NOT NULL, 
    Addr    VARCHAR(50) NOT NULL,
    Type VARCHAR(15),
    PRIMARY KEY (SSN, Addr)
);

DROP TABLE IF EXISTS PHONE_NO;
CREATE TABLE PHONE_NO (
    SSN    CHAR(9) NOT NULL, 
    Ph_No    CHAR(10) NOT NULL,
    Ph_Type VARCHAR(10),
    PRIMARY KEY (SSN, Ph_No)
);

ALTER TABLE ADDRESS ADD CONSTRAINT fk_address_member FOREIGN KEY (SSN) REFERENCES MEMBER(SSN) ON DELETE CASCADE;
ALTER TABLE PHONE_NO ADD CONSTRAINT fk_phoneno_member FOREIGN KEY (SSN) REFERENCES MEMBER(SSN) ON DELETE CASCADE;

DROP TABLE IF EXISTS MAINTAIN;
CREATE TABLE MAINTAIN (
    S_ID    INT NOT NULL, 
    ISBN    VARCHAR(13) NOT NULL,
    Can_Lend VARCHAR(3),
    Acquire VARCHAR(20),
    PRIMARY KEY (S_ID, ISBN)
);

ALTER TABLE MAINTAIN ADD CONSTRAINT fk_maintain_staff FOREIGN KEY (S_ID) REFERENCES STAFF(S_ID);
ALTER TABLE MAINTAIN ADD CONSTRAINT fk_maintain_staff_isbn FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN);

DROP TABLE IF EXISTS ISSUE_BOOK;
CREATE TABLE ISSUE_BOOK (
    Loan_No INT NOT NULL AUTO_INCREMENT,
    SSN    CHAR(9) NOT NULL, 
    ISBN    VARCHAR(13) NOT NULL,
    Issue_Date DATE,
    Due_Date DATE,
    Return_Date DATE,
    PRIMARY KEY (Loan_No, SSN, ISBN)
);

ALTER TABLE ISSUE_BOOK ADD CONSTRAINT fk_issuebook_member FOREIGN KEY (SSN) REFERENCES MEMBER(SSN);
ALTER TABLE ISSUE_BOOK ADD CONSTRAINT fk_issuebook_book FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN);

DROP TABLE IF EXISTS ISSUE_NOTICE;
CREATE TABLE ISSUE_NOTICE (
    SSN    CHAR(9) NOT NULL, 
    S_ID    INT NOT NULL,
    Notice  Varchar(500),
    Date DATE,
    PRIMARY KEY (SSN, S_ID)
);

ALTER TABLE ISSUE_NOTICE ADD CONSTRAINT fk_issuenotice_member FOREIGN KEY (SSN) REFERENCES MEMBER(SSN);
ALTER TABLE ISSUE_NOTICE ADD CONSTRAINT fk_issuenotice_staff FOREIGN KEY (S_ID) REFERENCES STAFF(S_ID);

DROP TABLE IF EXISTS FINE;
CREATE TABLE FINE (
    SSN    CHAR(9) NOT NULL, 
    Due    Decimal(10,2),
    PRIMARY KEY (SSN)
);

ALTER TABLE FINE ADD CONSTRAINT fk_fine_member FOREIGN KEY (SSN) REFERENCES MEMBER(SSN);

DROP TABLE IF EXISTS CHECK_INFO;
CREATE TABLE CHECK_INFO (
    S_ID    INT NOT NULL,
    ISBN    VARCHAR(13) NOT NULL,
    PRIMARY KEY (S_ID, ISBN)
);

ALTER TABLE CHECK_INFO ADD CONSTRAINT fk_checkinfo_staff FOREIGN KEY (S_ID) REFERENCES STAFF(S_ID);
ALTER TABLE CHECK_INFO ADD CONSTRAINT fk_checkinfo_catalogue FOREIGN KEY (ISBN) REFERENCES CATALOGUE(ISBN);