/*Ishita Kapur, UTA ID : 1001753123*/
/*5.1 To notify a member about the outstanding overdue book.*/
CREATE TRIGGER OVERDUE_BOOK
BEFORE INSERT OR UPDATE OF SSN, ISBN
    ON ISSUE_BOOK
FOR EACH ROW
    WHEN (NEW.SSN IN ( SELECT DISTINCT SSN FROM ISSUE_BOOK
        WHERE RETURN_DATE IS NULL AND DUE_DATE < NOW()))
        NOTIFY_MEMBER(NEW.SSN);


/*5.2 To notify a member about his membership renewal.*/
DROP TABLE IF EXISTS NOTIFYRENEWAL;
CREATE TABLE NOTIFYRENEWAL (
    SSN    CHAR(9) NOT NULL,
    Name    CHAR(25) NOT NULL,
    Email_ID CHAR(40) NOT NULL,
    Days_Remaining INT,
    PRIMARY KEY (SSN),
    FOREIGN KEY (SSN) REFERENCES MEMBER(SSN)
);

DELIMITER $$
CREATE EVENT renewal_daysrem
ON SCHEDULE
    EVERY 5 MINUTE
    STARTS '2020-05-02 00:00:00' ON COMPLETION PRESERVE ENABLE 
DO
BEGIN
    DELETE FROM NOTIFYRENEWAL;
    INSERT INTO NOTIFYRENEWAL (SSN, Email_ID, Name,Days_Remaining)
    SELECT SSN, Email_ID, Name, DATEDIFF(Validity, NOW()) as Days_Remaining
    FROM MEMBER
    WHERE Validity BETWEEN now() and adddate(now(),+30);
END $$
DELIMITER ;

CREATE TRIGGER MEMBER_RENEWAL
BEFORE INSERT OR UPDATE OF SSN
    ON NOTIFYRENEWAL
FOR EACH ROW
    WHEN (NEW.SSN IN (SELECT SSN FROM NOTIFYRENEWAL
        WHERE Days_Remaining = 7))
        NOTIFY_MEMBER(NEW.SSN);